# The action script for running riddlc
name: 'riddlc'
description: 'Run the riddlc translator'
inputs:
  command:  #
    description: 'The name of the command to pass to the riddlc compiler'
    required: true
    default: 'help'
  opt1:
    description: 'Optional argument 1'
    required: false
  opt2:
    description: 'Optional argument 2'
    required: false
  opt3:
    description: 'Optional argument 3'
    required: false
  opt4:
    description: 'Optional argument 4'
    required: false
  opt5:
    description: 'Optional argument 5'
    required: false
  opt6:
    description: 'Optional argument 6'
    required: false
  opt7:
    description: 'Optional argument 7'
    required: false
  opt8:
    description: 'Optional argument 8'
    required: false

runs:
  using: "composite"
  steps:
    - name: "Setup JRE"
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - run: |
        version="0.14.3"
        wget --quiet https://github.com/reactific/riddl/releases/download/${version}/riddlc-${version}.zip
        unzip riddlc-${version}.zip
        riddlc-${version}/bin/riddlc ${{ inputs.command }} ${{ inputs.opt1 }} ${{ inputs.opt2 }} ${{ inputs.opt3 }} ${{ inputs.opt4 }} ${{ inputs.opt5 }} ${{ inputs.opt6 }}  ${{ inputs.opt7 }} ${{ inputs.opt8 }}
      shell: bash
